version: '3.8'
services:
  server:
    image: saikrupaelate/server
    build: ./server
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql  # This should match the MySQL service name
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_DATABASE: devdb
    env_file:
      - ./server/.env
    entrypoint: ["sh", "wait-for-db.sh"]
    command: ["node", "index.js"]

  frontend:
    image: saikrupaelate/frontend
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - server

  mysql:
    image: mysql:5.7  # Specify a version for better consistency
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devdb
      MYSQL_USER: devuser       # Add this
      MYSQL_PASSWORD: devpass    # Add this
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"

volumes:
  db_data:

networks:
  default:
    name: app-network
    driver: bridge