name: CI/CD Pipeline - NodeReactApp

on:
  workflow_dispatch:  # Manual trigger via Actions button
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build & Push server image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/server:latest ./server
        docker push ${{ secrets.DOCKER_USERNAME }}/server:latest

    - name: Build & Push frontend image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend:latest ./frontend
        docker push ${{ secrets.DOCKER_USERNAME }}/frontend:latest

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          echo "Stopping containers..."
          docker-compose -f ~/DevStack-Lite/docker-compose.yml down || true
          docker-compose -f ~/NodeReact-DockerCI/docker-compose.yml down || true
          docker container stop $(docker ps -aq) || true
          docker container rm $(docker ps -aq) || true
          
          echo ">>> Remove all images..."
          docker rmi -f $(docker images -aq) || true

          echo ">>> Remove all volumes..."
          docker volume rm $(docker volume ls -q) || true

          echo ">>> Remove all networks (except default)..."
          docker network prune -f || true
          
          echo "Pruning images..."
          docker image prune -a -f || true
          docker volume prune -f || true

          echo ">>> Prune system (builder cache, etc)..."
          docker system prune -a -f --volumes || true

          echo ">>> Remove any old app folders..."
          rm -rf ~/DevStack-Lite || true 
          rm -rf ~/NodeReact-DockerCI || true

          echo "Cloning latest code..."
          git clone https://github.com/saikrupaelate/NodeReact-DockerCI.git ~/NodeReact-DockerCI

          echo "Pulling updated images..."
          docker pull ${{ secrets.DOCKER_USERNAME }}/server:latest
          docker pull ${{ secrets.DOCKER_USERNAME }}/frontend:latest

          echo "Starting containers..."
          cd ~/NodeReact-DockerCI
          docker-compose up -d
